# Generated by Django 5.0.6 on 2024-05-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coaching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=12)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.CharField(max_length=50)),
                ('personaje', models.CharField(choices=[('Scorpion', 'Scorpion'), ('Sub-Zero', 'Sub-Zero'), ('Liu Kang', 'Liu Kang'), ('Raiden', 'Raiden'), ('Johnny Cage', 'Johnny Cage'), ('Shao Kahn', 'Shao Kahn'), ('Omniman', 'Omniman'), ('Kung Lao', 'Kung Lao'), ('Reptile', 'Reptile'), ('Smoke', 'Smoke'), ('Li Mei', 'Li Mei'), ('Ashrah', 'Ashrah'), ('Kenshi', 'Kenshi'), ('Nitara', 'Nitara'), ('Geras', 'Geras'), ('Havik', 'Havik'), ('Kitana', 'Kitana'), ('Mileena', 'Mileena'), ('Rain', 'Rain'), ('Sindel', 'Sindel')], default='Scorpion', max_length=20)),
                ('rank', models.CharField(max_length=6)),
                ('city', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen_titulo', models.ImageField(upload_to='mortalweb/static/imagenes')),
                ('imagen_personaje', models.ImageField(upload_to='mortalweb/static/imagenes')),
                ('imagen_fondo', models.ImageField(upload_to='mortalweb/static/imagenes')),
            ],
        ),
    ]
