# Generated by Django 5.0.6 on 2024-06-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortalweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaje',
            name='imagen_fondo',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='personaje',
            name='imagen_personaje',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='personaje',
            name='imagen_titulo',
            field=models.ImageField(upload_to=''),
        ),
    ]
