# Generated by Django 5.0.6 on 2024-06-03 18:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortalweb', '0002_alter_personaje_imagen_fondo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaje',
            name='biography',
            field=models.TextField(default='Biografía por defecto', max_length=1600, validators=[django.core.validators.MinLengthValidator(1000)]),
        ),
        migrations.AddField(
            model_name='personaje',
            name='introduction',
            field=models.TextField(default='Introducción por defecto', max_length=400, validators=[django.core.validators.MinLengthValidator(200)]),
        ),
        migrations.AlterField(
            model_name='coaching',
            name='personaje',
            field=models.CharField(choices=[('Scorpion', 'Scorpion'), ('Sub-Zero', 'Sub-Zero'), ('Liu Kang', 'Liu Kang'), ('Raiden', 'Raiden'), ('Johnny Cage', 'Johnny Cage'), ('Shao Kahn', 'Shao Kahn'), ('Omniman', 'Omniman'), ('Kung Lao', 'Kung Lao'), ('Reptile', 'Reptile'), ('Smoke', 'Smoke'), ('Li Mei', 'Li Mei'), ('Ashrah', 'Ashrah'), ('Kenshi', 'Kenshi'), ('Nitara', 'Nitara'), ('Geras', 'Geras'), ('Havik', 'Havik'), ('Kitana', 'Kitana'), ('Mileena', 'Mileena'), ('Rain', 'Rain'), ('Sindel', 'Sindel')], default='Mileena', max_length=20),
        ),
    ]
